qwen:
  model_path: "Qwen3-VL-8B-Instruct"
  target_desc: "打斗，骑自行车，骑摩托车，机动车，跳远，抢夺，小推车，翻越栏杆，摔倒，向上抛掷物品，滑滑板，快速奔跑，挥舞长棍"
  # "打斗，骑自行车，骑摩托车，机动车，跳远，抢夺，小推车，翻越栏杆，摔倒，向上抛掷物品，滑滑板，快速奔跑，挥舞长棍"
  # "打斗，骑自行车，骑摩托车，机动车，跳跃，抢夺，小推车，翻越栏杆，摔倒，滑滑板的人"
  # "追逐，打斗，奔跑，骑自行车，骑摩托车，滑滑板，驾驶机动车，跳跃，抢夺，推车，挥舞物品，翻越栏杆"
  # "打斗，骑自行车，骑摩托车，机动车，跳跃，抢夺，小推车，翻越栏杆，摔倒，向上抛掷物品，滑滑板的人"

  # "追逐，打斗，奔跑，骑自行车，骑摩托车，滑滑板，机动车，跳跃，投掷，抢夺，摔倒，推车，挥舞物品，翻越"
  max_new_tokens: 256

sam2:
  model_cfg: "configs/sam2.1/sam2.1_hiera_l.yaml"
  checkpoint: "./checkpoints/sam2.1_hiera_large.pt"
  multimask_output: false

selector:
  alpha: 0.9
  beta: 0.1
  min_score: 0.6
  top_k_frames: 1
  max_targets_per_frame: 2
  count_bonus: 0.03
  min_frame_gap: 30
  merge_iou_thresh: 0.8

candidate_selector:
  high_ratio: 0.8
  mid_ratio: 0.3
  low_ratio: 0.3
  uniform_interval: 0

pipeline:
  batch_size: 4
  queue_size: 32
  visualize_detector: true

data:
  dataset_name: "SHT"
  videos_root: "/data/users/wjq/datasets/shanghaitech/testing/frames"
  # "/data/users/wjq/datasets/shanghaitech/testing/frames"
  output_root: "./outputs/improved_temploc0.8"
  track_txt_root: "./tracks/improved_temploc0.8"
  detector_stage2_vis_root: "./outputs/detector_stage2_vis_noconfidencerule"
  detector_stage2_json_root: "./output_json_detector/detector_stage2_json_noconfidencerule"
  ann_obj_id: 1
